# Generated by Django 4.1.4 on 2023-02-04 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0002_agenda_alter_medico_crm_alter_medico_email_consulta_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('medico', 'dia')},
        ),
    ]
