# Generated by Django 4.1.4 on 2023-02-03 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agendamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='email',
            new_name='horario',
        ),
    ]
